-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Aug 14, 2015 at 12:11 AM
-- Server version: 5.5.44-0ubuntu0.14.04.1
-- PHP Version: 5.5.9-1ubuntu4.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `tnp`
--

-- --------------------------------------------------------

--
-- Table structure for table `erp`
--

CREATE TABLE IF NOT EXISTS `erp` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cell1` varchar(200) NOT NULL,
  `type` varchar(200) NOT NULL,
  `cell3` varchar(200) NOT NULL,
  `company` varchar(200) NOT NULL,
  `description` varchar(200) NOT NULL,
  `cell6` varchar(200) NOT NULL,
  `date` varchar(200) NOT NULL,
  `link` varchar(200) NOT NULL,
  `cell9` varchar(200) NOT NULL,
  `cell10` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=140 ;

--
-- Dumping data for table `erp`
--

INSERT INTO `erp` (`id`, `cell1`, `type`, `cell3`, `company`, `description`, `cell6`, `date`, `link`, `cell9`, `cell10`) VALUES
(1, '154', 'PLACEMENT', 'Urgent', 'DEFERRED PLACEMENT POLICY', 'PLEASE FIND ATTACHED THE RULES FOR DEFERRED PLACEMENT POLICY.INTERESTED STUDENTS ARE ADVISED TO SEE THE SAME APPLY ACCORDINGLY.CHAIRMAN, CDC', '90018', '13-08-2015 16:21', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/154.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(2, '153', 'INTERNSHIP', 'Schedule', 'Linkedin', 'Shortlist  for online  test  of Linked in is  attached.Find below the instructions to follow for smooth functioning of the LinkedIn intern hiring process1. All  the shortlisted students appearing for ', '90033', '13-08-2015 15:28', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/153.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(3, '152', 'PLACEMENT', 'PPT/Workshop/Seminars etc', 'ABCO Advisory Services India Private Ltd', '', '90018', '13-08-2015 15:25', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(4, '150', 'INTERNSHIP', 'Reminder', 'Schlumberger', '', '90033', '13-08-2015 12:26', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(5, '149', 'INTERNSHIP', 'CV Submission', 'Adobe', 'Adobe invites application for summer internship selection (May-July, 2016)Interested and eligible students as per internship notification form (INF) available in their ERP account are required to subm', '90033', '13-08-2015 12:09', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(6, '148', 'INTERNSHIP', 'Urgent', 'SOFT SKILL PROGRAMME', 'ALL INTERESTED STUDENTS (ALL COURSES &amp; ALL DEPTT) FOR SUMMER INTERNSHIP (MAY-JULY, 2016) ARE ADVISED TO SEE THE ATTACHED POSTER AND ATTEND THE SOFT SKILL PROGRAMME POSITIVELY ON 14TH AUGUST, 2015 ', '90018', '13-08-2015 09:49', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/148.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(7, '147', 'PLACEMENT', 'Urgent', 'SOFT SKILL PROGRAMME', 'ALL INTERESTED STUDENTS (ALL COURSES &amp; ALL DEPTT) FOR FINAL PLACEMENT ARE ADVISED TO SEE THE ATTACHED POSTER AND ATTEND THE SOFT SKILL PROGRAMME POSITIVELY ON 14TH AUGUST, 2015 (5.30 PM) AT KALIDA', '90018', '13-08-2015 09:48', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/147.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(8, '146', 'INTERNSHIP', 'Urgent', 'WORLDQUANT', 'ALL STUDENTS ELIGIBLE FOR INTERNSHIP THROUGH CDC ARE ADVISED TO REPORT TO V1 IMMEDIATELY FOR PPT OF WORLDQUANT, OTHERWISE, ACTION WILL TAKEN AS RULE.CHAIRMAN, CDC', '90018', '12-08-2015 19:05', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(9, '145', 'PLACEMENT', 'Revised', 'Shell India Markets Pvt Ltd', 'THE QUERIES IN RESPECT OF VALIDITY OF THEIR APPLICATION IN SHELL, STUDENTS ARE ADVISED TO FILL THE INFORMATION TO THE BELOW LINK :https://goo.gl/ckwV24PLEASE IGNORE OUR EARLIER CIRCULAR.CHAIRMAN, CDC', '90018', '12-08-2015 18:27', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(10, '144', 'PLACEMENT', 'Urgent', 'WorldQuant', 'THE FOLLOWING STUDENTS ARE ALSO ELIGIBLE TO ATTEND THE PPT OF WORLDQUANT.B. TECH &amp; DUAL DEGREE : ECEDUAL DEGREE : FINANCIAL ENGGINTERESTED STUDENTS ARE ADVISED TO ATTEND THE PPT TODAY 6.30 PM AT V', '90018', '12-08-2015 18:21', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(11, '143', 'INTERNSHIP', 'General', 'CDC Student Representatives', 'A Departmental CDC Student Representatives Team will be formed for the year 2015-2016 for helping the Career Development Centre.The students eligible are: 3rd year student of B. Tech/Dual Degree/Integ', '90018', '12-08-2015 16:13', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/143.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(12, '142', 'PLACEMENT', 'PPO', 'LINKEDIN', 'LINKEDIN have extended 03 (THREE)  Pre-placement Offer (PPO) to the following students:112CS10058PRITHWISH MUKHERJEE212CS10012BEHATI ASHUTOSH SUSHIL311CS30042PRANAY YERRA HASSANCTC : INR 20,00,000 PER', '90018', '12-08-2015 10:14', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(13, '141', 'INTERNSHIP', 'Urgent', 'SOFT SKILL PROGRAMME', 'As per the request of our students community and from our previous year experience, CDC is planning to organize soft skill training program for session 2015-16 with the help of professional agencies. ', '90018', '12-08-2015 09:33', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(14, '140', 'PLACEMENT', 'Urgent', 'SOFT SKILL PROGRAMME', 'As per the request of our students community and from our previous year experience, CDC is planning to organize soft skill training program for session 2015-16 with the help of professional agencies. ', '90018', '12-08-2015 09:32', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(15, '139', 'INTERNSHIP', 'Result', 'American Express', 'American Express have selected the following students for summer internship 2016.1. Udai Bharadwaj    13EE100532. Anuj Menta        12MA200073. Srinidhi          13CS300344. Raunak Chitlangia 13EC3003', '90033', '12-08-2015 07:38', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(16, '138', 'INTERNSHIP', 'Shortlist', 'American Express', 'The  following additional students shortlisted  for  personal interviews.1. Ayush Pandey  12MA200092. Raunak Chitlangia 13EC30030These  students advised to report at CDC office 8.45 p.m. today to atte', '90033', '11-08-2015 20:12', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(17, '137', 'INTERNSHIP', 'CV Submission', 'MetricStream', 'The  dead  line for  CV  submission of Metric stream has been extended  up to  4.00 P.M. on 14th August, 2015 .The  detail of  stipend and  Job  description will be  discussed in  pre placement  talk ', '90033', '11-08-2015 19:54', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(18, '136', 'INTERNSHIP', 'Shortlist', 'American  Express', 'Attached find the Shortlist of American  Express for Summer Internship Interview process.All the shortlisted students should report at CDC office at 6.45  p.m. sharp today to attend the selection proc', '90033', '11-08-2015 18:04', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/136.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(19, '135', 'PLACEMENT', 'PPO', 'TATA STEEL LTD', '', '90018', '11-08-2015 17:22', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(20, '134', 'INTERNSHIP', 'CV Submission', 'Linkedin', 'Linkedin invites application for summer internship selection (May-July, 2016)The  company will conduct online test on 13.08.2015  as mentioned below.Date: 13.08.2015Time:  7.00 P.M.  to  8.00 P.M.Venu', '90033', '11-08-2015 17:08', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(21, '133', 'INTERNSHIP', 'PPT/Workshop/Seminars etc', 'World Quant', 'World Quant is visiting the campus on 12th August, 2015 for their Pre Presentation Talk Date : 12th August, 2015 [ Wednesday]Venue : V-1 HALL OF VIKRAMSHILATime: 6.30 P.M.All interested 3rd Year B. Te', '90033', '11-08-2015 15:52', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(22, '132', 'PLACEMENT', 'PPT/Workshop/Seminars etc', 'WorldQuant Research India Pvt.', '5TH YEAR INTEGRATED M. SC. IN ECONOMICS ARE ALSO ELIGIBLE FOR FINAL PLACEMENT OF WORLDQUANT. INTERESTED STUDENTS ARE ADVISED TO ATTEND THE PPT AS MENTIONED OUR EARLIER CIRCULAR POSITIVELY.CHAIRMAN, CD', '90018', '11-08-2015 15:45', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(23, '131', 'PLACEMENT', 'Urgent', 'Shell India Markets Pvt Ltd', 'Students who have queries with respect to the validity of their application in Shell are requested to write to the email id: tnp-placecom@hijli.iitkgp.ernet.in in the following format:Name:Roll No.:Sh', '90018', '11-08-2015 12:15', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(24, '130', 'PLACEMENT', 'PPO', 'XEROX', 'XEROX have extended 02 (TWO)  Pre-placement Offer (PPO) to the following students:112CS10060KOUSHIK CHATTOPADHYAY211CS30043SACHIN KUMARCTC : INR 21,00,000 P.A.The above students  are required to submi', '90018', '11-08-2015 10:33', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(25, '129', 'INTERNSHIP', 'CV Submission', 'Schlumberger', 'It  is  observed  that  some students  applied  for Schlumberger are not  uploaded   their photographs in their  CV"s. They  are  advised  to upload  their CV with the  photograph immediately or  else', '90033', '11-08-2015 09:41', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(26, '128', 'INTERNSHIP', 'CV Submission', 'XEROX RESEARCH CENTER INDIA', 'Xerox Research Centre India invites application for summer internship selection (May-July, 2016)Interested and eligible students as per internship notification form (INF) available in their ERP accoun', '90033', '10-08-2015 18:13', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(27, '127', 'PLACEMENT', 'PPO', 'DataRPMindia Pvt Ltd', 'DataRPMindia Pvt Ltd have extended 01(one)  Pre-placement Offer (PPO) to the following student:11IM3FP13NEVIN K JCTC : INR 13,00,000 PER ANNUAMThe above student  is required to submit his written acce', '90018', '10-08-2015 16:32', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(28, '126', 'PLACEMENT', 'PPO', 'Deutsche Bank', 'Deutsche Bank have extended 09 (NINE)  Pre-placement Offer (PPO) to the following students:112BT10015KRITARTH JHA212CE10029NOEL MATHEW PAUL312EE10018HIMANSHU AGARWAL4 11HS20014KRATI AGARWAL511HS20020N', '90018', '10-08-2015 16:27', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(29, '125', 'PLACEMENT', 'PPO', 'FLIPKART', 'FLIPKART have extended 01 (ONE)  Pre-placement Offer (PPO) to the following students:114CS60R38ABHISHEK SIKCHICTC is in the attachment.The above student  is required to submit his written acceptance/r', '90018', '10-08-2015 16:16', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/125.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(30, '124', 'PLACEMENT', 'PPO', 'JSW', 'JSW have extended 02 (TWO)  Pre-placement Offer (PPO) to the following students:112CH10016KASTUR BHATTACHARJEE212MF10011MUKESH PRASADCTC :  Cost-to-Company (CTC) for the first year of the program woul', '90018', '10-08-2015 16:11', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(31, '123', 'PLACEMENT', 'PPO', 'TEXAS INSTRUMENTS', 'Mr. Jayathi Sai Ram Prakash is asked to collect the PPO offer from the CDC office by 13/8/15 (time: 3.30pm to 5pm)  by producing institute identity card.Chairman, CDC', '89023', '10-08-2015 15:59', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(32, '122', 'INTERNSHIP', 'Offer letters', 'Texas  Instruments', 'The  following students  offered Summer  Internship- 2016  at  Texas  Instruments are  advised to collect their offer letters with other gifts  from CDC Section by 11th August, 2015.1. Sachin Purohit2', '90033', '10-08-2015 15:39', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(33, '121', 'INTERNSHIP', 'CV Submission', 'Schlumberger', '', '90033', '10-08-2015 14:55', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(34, '120', 'PLACEMENT', 'PPT/Workshop/Seminars etc', 'CISCO''s iCode Coding Challenge', '', '90018', '10-08-2015 12:57', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(35, '119', 'PLACEMENT', 'PPO', 'TEXAS INSTRUMENTS', 'TEXAS INSTRUMENTS have extended 01 (ONE) more  Pre-placement Offer (PPO) to the following student:11EC32002NUTHAKKI SRINIVASA SHASHANKCTC : RS. 1389836/-The above student  is required to submit his wr', '90018', '10-08-2015 12:26', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(36, '118', 'INTERNSHIP', 'CV Submission', 'Schlumberger', 'Schlumberger Asia Services Ltd. invites application for summer internship selection (May-July, 2016)Attach your recent passport photograph on the  write side  corner of  your  CV and submit through ER', '90033', '10-08-2015 11:18', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(37, '117', 'PLACEMENT', 'PPT/Workshop/Seminars etc', 'WorldQuant', '', '90018', '10-08-2015 10:58', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(38, '115', 'PLACEMENT', 'PPT/Workshop/Seminars etc', 'MetricStream Infotech', 'MetricStream Infotech is visiting the campus for Pre-placement Talk with final year students who are passing out June, 2016. Date : 12th July, 2015 [ WEDNESDAY] Venue : V1 Time: 5.30 p.m.  sharpPROFIL', '90018', '10-08-2015 10:55', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(39, '114', 'INTERNSHIP', 'PPT/Workshop/Seminars etc', 'MetricStream', 'MetricStream  is visiting the campus on 12th August, 2015 for their Pre Presentation Talk  in connection  with  Summer  Internship-2016.Date : 12th  August, 2015 [ Wednesday]Venue : V-1 HALL OF VIKRAM', '90033', '10-08-2015 10:17', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(40, '113', 'PLACEMENT', 'PPO', 'AXSIOM', 'AXSIOM  have extended 04 (FOUR)   Pre-placement Offer (PPO) to the following students:112NA10003ANKIT GAHLAWAT212NA10022LAVYA GARG311GG20002ABHILASH MITTAL411EC35007MOHIT AGARWALThe CTC would be 9L pe', '90018', '10-08-2015 10:10', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(41, '112', 'INTERNSHIP', 'PPT/Workshop/Seminars etc', 'American Express', 'American Express is visiting the campus on 11th August,2015 in connection with summer internship -2016 selections.The programme is as followsDate: 11th August, 20155.30 P.M. : PPT at S.N. Bose Auditor', '90033', '10-08-2015 09:53', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(42, '111', 'PLACEMENT', 'PPO', 'TEXAS INSTRUMENTS', 'TEXAS INSTRUMENTS have extended 01 (ONE)   Pre-placement Offer (PPO) to the following students:112EC10024J SAI RAM PRAKASHPROFILE : DESIGN ENGINEERCTC : 1389836The above student is advised to submit h', '90018', '07-08-2015 15:42', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(43, '110', 'INTERNSHIP', 'Urgent', 'American Express', 'The following students are directed to meet Chairman, CDC by 6.00 PM today (7th August 2015)otherwise they will be marked as defaulter.Jeenu Grover: 13CS30042Ashish Sharma: 13CS30043Chairman, CDC', '11009', '07-08-2015 15:10', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(44, '109', 'PLACEMENT', 'PPO', 'QUALCOMM', 'QUALCOMM have extended 04 (FOUR)   Pre-placement Offer (PPO) to the following students:112EC10036NIKHIL KEDIA212EC10066AJAY AGARWAL312EE10009DEEPANSHU PARIYANI411EE35002PRADEEP AGRAWALCTC : RS.13.50 L', '90018', '07-08-2015 12:21', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(45, '107', 'PLACEMENT', 'PPO', 'EDGEVERVE', 'EDGEVERVE have extended 01 (ONE)   Pre-placement Offer (PPO) to the following student:Mr. Sabyasachi Behra (Roll No 12CS10042)Below are the details:Role Designation  Member of Technical StaffCompensat', '90018', '06-08-2015 17:28', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(46, '106', 'INTERNSHIP', 'Result', 'IBM Research', 'IBM Research have selected the following students for summer internship 2016.1. AKASH MANDAL2. SAYAN MUKHOPADHYAY3. SAMUEL SURAJ BUSHI4. VISHNU CHOUDHARY"Hearty Congratulations"The above students are ', '90033', '06-08-2015 11:08', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(47, '105', 'INTERNSHIP', 'Reminder', 'American Express', 'Online test schedule of American Express.Test Date  06th August 2015Test Duration  45 MinsVenue: PC Labs of Takshila Complex ( sitting arrangement attached)Window for taking the test - 6 pm to 6:45pm ', '90033', '06-08-2015 09:57', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/105.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(48, '103', 'INTERNSHIP', 'Result', 'Intuit', 'Intuit have selected the following students for summer internship 2016. 1. KESHAV AGARWAL 2. ABINASH MEHER3. AMANDEEP SINGH 4. ABHISHEK SAINI 5. RAGHAV AGARWAL "Hearty Congratulations" The above stude', '11009', '06-08-2015 09:19', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(49, '102', 'INTERNSHIP', 'Shortlist', 'Intuit', 'Attached find the Shortlist of Intuit for Summer Internship Interview process.All the shortlisted students should report at CDC office  at  10.15 p.m. sharp today  to attend the selection process in f', '90033', '05-08-2015 22:01', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/102.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(50, '101', 'INTERNSHIP', 'Schedule', 'IBM Research', 'The following students are shortlisted for telephonic interviews of IBM Research in connection with Summer Internship selection.SAMUEL SURAJ BUSHI 13CS10044ANANTH PRANIHITH POTULA 13CS10011RAGHAV AGAR', '90033', '05-08-2015 16:47', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(51, '99', 'INTERNSHIP', 'Schedule', 'American Express', 'American Express   will conduct online test  on   06th August,2015  in connection with  summer  internship -2016  selections. The  shortlist  for  online test is attached.The  programme  is  as  follo', '90033', '05-08-2015 16:20', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/99.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(52, '98', 'INTERNSHIP', 'Shortlist', 'Intuit', 'THE SHORTLIST FOR ONLINE TEST  IN  CONNECTION WITH  SUMMER  INTERNSHIP SELECTION OF  INTUIT IS  ATTACHED.ALL THE SHORTLISTED STUDENTS SHOULD NOTE AND ATTEND THE TEST AS PER THE  SCHEDULE GIVEN IN THE ', '90033', '04-08-2015 17:28', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/98.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(53, '97', 'INTERNSHIP', 'Date extension', 'American Express', 'Dear Students,Deadline for applying on American Express career portal has been further extended till 23:59 PM today (3rd August, 2015). In case you face any technical issues in applying, try using Int', '11009', '03-08-2015 19:42', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(54, '96', 'INTERNSHIP', 'PPT/Workshop/Seminars etc', 'Intuit', 'Intuit  is  visiting the campus  on   05th August,2015  in connection with  summer  internship -2016  selections. The  programme  is  as  followsDate:  05th August, 20155.30 P.M. :  PPT at S.N. Bose  ', '90033', '03-08-2015 15:19', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(55, '95', 'INTERNSHIP', 'Result', 'Nomura', 'Nomura has  extended one more  offer  to the wait listed student Sidhartha Satapathy  for  summer  internship-2016."Hearty Congratulations"Sidhartha required to submit his written acceptance of the of', '90033', '03-08-2015 09:54', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(56, '94', 'INTERNSHIP', 'Result', 'Texas Instruments', 'Texas Instruments  have selected the following students for summer internship 2016. 1. Sagar kumashi2. Shantanu Gawande3. Apoorv Sinha4. GDM Nagarjuna5. Ishmeet Singh6. Manish Mustafi7. Suryateja8. Vi', '90033', '02-08-2015 19:55', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(57, '93', 'INTERNSHIP', 'Additional requirement', 'Texas Instruments', 'Texas Instruments  has considered  the  following  additional students for the  P.I. round.1. Sagar Ramesh Kumashi2. Vikash3. Abhishek Sinha4. Manny Jain5. Shashwat Pandey6. Manasani Nikitha7. Saion K', '90033', '02-08-2015 19:48', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(58, '92', 'INTERNSHIP', 'Urgent', 'American Express', 'It has been informed to CDC by American Express that-1) Some of applicants have not filled ''IIT KGP'' in Education Level. IIT KGP should be filled in the first entry followed by your previous schools d', '90033', '02-08-2015 15:33', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(59, '91', 'INTERNSHIP', 'Date extension', 'IBM Research  &  Intuit', 'The deadline for CV submission in connection with summer internship selection of following  companies  has been extended till 12.00 A.M. on 02.08.2015.1. IBM Research2. IntuitAll the concerned should ', '90033', '02-08-2015 12:54', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(60, '90', 'INTERNSHIP', 'Shortlist', 'Texas  Instruments', 'Shortlist  of Texas  Instruments is   for  personal  interviews  is attached. Students  should  report CDC  office sharp  at        11.00 A.M. to  attend  the  selection process.Students   should be  ', '90033', '02-08-2015 10:02', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/90.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(61, '89', 'INTERNSHIP', 'Result', 'REVISED-1st Day (1st Aug.) Companies', 'Results of Different companies visited on 1st August, 2015 in connection with Summer Internship Selection-2016. Deutsche Bank ( DB Centre). 1 Naitik Jain 2. Yash Kariwal 3. Harshav Raj 4. Triyansha V.', '11009', '01-08-2015 23:27', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(62, '87', 'INTERNSHIP', 'Urgent', 'American Express', 'Attached find the Revised instructions to fill the online  form  of  American Express in  connection with Summer Internship Selection=2016.The online form  should be filled within the scheduled time a', '90033', '01-08-2015 23:20', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/87.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(63, '85', 'PLACEMENT', 'PPT/Workshop/Seminars etc', 'Texas Instruments', 'Texas  Instruments  is visiting the campus for their Pre  Placement  Talk with final year students who are passing out June, 2016.Date : 02nd August, 2015 [ SUNDAY]Venue : V-1  HALL OF  VIKRAMSHILATim', '90033', '01-08-2015 18:40', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(64, '84', 'INTERNSHIP', 'Urgent', '1st Day Companies', 'Venues for  the selection process is  attached for  information of all concerned.Chairman, CDC', '90033', '01-08-2015 05:42', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/84.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(65, '83', 'INTERNSHIP', 'General', 'Bus Service', 'Bus service is available from all the hostel to Nalanda complex.this is for your information.', '11009', '01-08-2015 05:40', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(66, '82', 'INTERNSHIP', 'Shortlist', 'Microsoft', 'The students who have been shortlisted for Microsoft IDC and Microsoft MSIT - Groupfly have to report in Nalanda by 5:30am and students who have been shortlisted for Microsoft MSIT - Interview should ', '90033', '01-08-2015 01:10', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(67, '81', 'INTERNSHIP', 'Shortlist', 'Nomura', 'Attached find the Shortlist of Nomura for Summer Internship selection process.All the shortlisted students should report at Nalanda Complex at 8.00 a.m. sharp on 01st August, 2015 to attend the select', '90033', '01-08-2015 00:58', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/81.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(68, '79', 'INTERNSHIP', 'Shortlist', 'DB Centre', 'Attached find the Shortlist of DB Centre for Summer Internship GD process.All the shortlisted students should report at Nalanda Complex at 5.30 a.m. sharp on 01st August, 2015 to attend the GD process', '90033', '01-08-2015 00:15', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/79.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(69, '78', 'INTERNSHIP', 'Shortlist', 'RB', 'Attached find the Shortlist of RB for Summer Internship GD process.All the shortlisted students should report at Nalanda Complex at 5.30 a.m. sharp on 01st August, 2015 to attend the GD process in for', '90033', '01-08-2015 00:12', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/78.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(70, '77', 'INTERNSHIP', 'Shortlist', 'Microsoft', 'Attached find the Shortlist of Microsoft for Summer Internship selection  process.All the shortlisted students should report at Nalanda Complex at 5.30 a.m. sharp on 01st August, 2015 to attend the se', '90033', '01-08-2015 00:08', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/77.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(71, '76', 'INTERNSHIP', 'Shortlist', 'Goldman Sach', 'Attached find the Shortlist of Goldman Sach (Stg.) for Summer Internship GD/ Selection process.All the shortlisted students should report at Nalanda Complex at 8.30 a.m. sharp on 01st August, 2015 to ', '90033', '01-08-2015 00:06', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/76.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(72, '75', 'INTERNSHIP', 'Shortlist', 'ITC Limited', 'Attached find the Shortlist of ITC Limited for Summer Internship GD process.All the shortlisted students should report at Nalanda Complex at 5.30 a.m. sharp on 01st August, 2015 to attend the GD proce', '90033', '01-08-2015 00:03', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/75.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(73, '74', 'INTERNSHIP', 'Shortlist', 'Hindustan Unilever (HUL)', 'Attached find the Shortlist of   Hindustan Unilever (HUL)  for Summer Internship GD process. All the shortlisted students should  report at Nalanda Complex at 5.30  a.m. sharp   on  01st  August, 2015', '90033', '01-08-2015 00:00', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/74.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(74, '73', 'INTERNSHIP', 'Urgent', 'Selection process of 1st August', 'All students who get shortlisted for selection process are directed to Report to Nalanda Complex by 5.30 AM positively.Students who will fail to report at Nalanda complex by 5.30 AM will be marked as ', '11009', '31-07-2015 22:47', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(75, '72', 'INTERNSHIP', 'Urgent', '1st  Day (1st Aug.)  Companies', 'The shortlist for the companies (having selection process on 01.08.2015) will be displayed on ERP notice board around 11.30 p.m. today.Students  should carry a  hard copy  of  their CV  to  attend the', '90033', '31-07-2015 21:07', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(76, '70', 'INTERNSHIP', 'Re-schedule', 'DB  Centre', 'The  Pre presentation of DB Centre  for  summer  internship   scheduled to be held  held at  V-1 hall of Vikrramshila  has been sifted to Kalidas AuditoriumThe time of the  PPT  remain same  i.e 8.15 ', '90033', '31-07-2015 17:46', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(77, '69', 'INTERNSHIP', 'PPT/Workshop/Seminars etc', 'Texas Instruments', 'TEXAS INSTRUMENTS is visiting the campus for  Summer  Internship- 2016  selection. The  program  is  as  follows.Date : 2nd AUGUST, 2015 [SUNDAY]PPT:  9.00 a.m. ( V-1 Hall of  Vikram Shila  Complex)Fo', '90033', '31-07-2015 17:09', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(78, '68', 'INTERNSHIP', 'Urgent', 'All Companies', 'The following students have not attended the test of Goldman Sachs after submitting their CVs for the company. These students have been marked as defaulters. These students will not be allowed to appe', '11009', '31-07-2015 16:39', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(79, '67', 'PLACEMENT', 'General', 'Shell India Markets Pvt Ltd', 'THE POSTER OF SHELL INDIA FOR THEIR COMPUTATIONAL PH.D PROGRAMME IS IN THE ATTACHMENT FOR INFORMATION OF ALL INTERESTED STUDENTS OF FINAL YR. DUAL DEGREE AND M. TECH.CHAIRMAN, CDC', '90018', '31-07-2015 12:43', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/67.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(80, '66', 'INTERNSHIP', 'Re-schedule', 'As  mentioned', 'Re- Schedule of Pre presentation talks of different companies in connection with Summer Internship Selection-2016.Date: 31st July, 2015Name of the Company TimeVenueHindustan Unilever 5.45 P.M to 6.45 ', '90033', '31-07-2015 09:45', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(81, '64', 'PLACEMENT', 'PPO', 'SPRINKLR', '', '90018', '30-07-2015 18:12', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(82, '63', 'INTERNSHIP', 'Re-schedule', 'Microsoft', 'The Pre Presentation of Microsoft in connection of  Summer  Internship has  been  rescheduled as   follows.Date: 31st August, 2015Time: 9.30 P.M.  to 10.30 P.M.Venue: V-2 Hall of  Vikramshila ComplexA', '90033', '30-07-2015 16:11', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(83, '62', 'PLACEMENT', 'PPO', 'Futures First Info Services Pvt. Ltd.', 'THE DEADLINE FOR ACCEPTING THE PRE PLACEMENT OFFER OF FUTURE FIRST HAS BEEN EXTENDED TILL 4.00 PM ON 7TH AUGUST, 2015.CHAIRMAN, CDC', '90018', '30-07-2015 15:48', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(84, '61', 'PLACEMENT', 'PPT/Workshop/Seminars etc', 'Shell India Markets Pvt Ltd', 'Shell India Markets Pvt Ltd is visiting the campus for workshop a Computational Sciences PhD program in The Netherlands  who are passing out June, 2016. Date : 2ND AUGUST, 2015 [SUNDAY] Venue : V1 Tim', '90018', '30-07-2015 14:58', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(85, '60', 'INTERNSHIP', 'CV Submission', 'Intuit', 'Intuit invites application for summer internship selection (May-July, 2016)Interested and eligible students as per internship notification form (INF) available in their ERP account are required to sub', '90033', '30-07-2015 14:55', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(86, '59', 'INTERNSHIP', 'CV Submission', 'IBM Research', 'IBM Research invites application for summer internship selection (May-July, 2016)Interested and eligible students as per internship notification form (INF) available in their ERP account are required ', '90033', '30-07-2015 14:52', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(87, '57', 'PLACEMENT', 'PPT/Workshop/Seminars etc', 'Shell India Markets Pvt Ltd', 'Shell India Markets Pvt Ltd is visiting the campus for Pre Placement Talk/workshop for  Final Placements who are passing out June, 2016. Date : 2ND AUGUST, 2015 [SUNDAY] Venue : V1 Time: 1.00 p.m. sha', '90018', '30-07-2015 12:50', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(88, '55', 'INTERNSHIP', 'Urgent', 'Goldman Sach ( Stg.)', 'Sitting arrangement  for Written  Test of Goldman Sach ( Stg.) in  connection with Summer  Internship Selection is attached.Date:  30.07.2015Time :  Sharp 8.00 P.M.Venue:  V1, V2, V3 &amp; V4 ( Vikram', '90033', '30-07-2015 11:33', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/55.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(89, '54', 'PLACEMENT', 'PPT/Workshop/Seminars etc', 'Deutsche CIB Centre', 'Deutsche CIB Centre   is visiting the campus for Pre Placement Talk for  Final Placementswho are passing out June, 2016. Date : 31st  JULY, 2015 [ FRIDAY] Venue : KALIDAS AUDITORIUM Time: 9.15 p.m. CT', '90018', '30-07-2015 10:46', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(90, '53', 'PLACEMENT', 'PPT/Workshop/Seminars etc', 'GOLDMAN SACHS', 'GOLDMAN SACHS   is visiting the campus for Pre Placement Talk for  Final Placementswho are passing out June, 2016. Date : 31st  JULY, 2015 [ FRIDAY] Venue : KALIDAS AUDITORIUM Time: 5.30 p.m.CTC : Rs.', '90018', '30-07-2015 10:44', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(91, '52', 'PLACEMENT', 'PPO', 'CREDIT SUISSE', 'CREDIT SUISSE have extended 02 (TWO)   Pre-placement Offers (PPO) to the following students:Name of the student      - Lakshya Kalra, 12IM10015Designation                  - ENO, Prime ServicesLocatio', '90018', '30-07-2015 10:09', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(92, '51', 'INTERNSHIP', 'Schedule', 'Goldman Sachs-Stg.- Test', 'The written test of Goldman Sachs-Stg. is scheduled today (30th july 2015) @ 8.00 PM at the Vikramshila complex (v1,v2,v3 &amp; V4). All the students who have submited their CV for the organisation ar', '11009', '30-07-2015 09:26', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(93, '50', 'INTERNSHIP', 'PPT/Workshop/Seminars etc', 'ITC Limited', 'ITC LIMITED is visiting the campus for their Leadership Talk  in  connection with Summer  Internship Selection-2016.Date : 30th JULY, 2015 [ THURSDAY]Venue : KALIDAS AUDITORIUMTime: 6.45 p.m.All the  ', '90033', '29-07-2015 16:30', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(94, '49', 'PLACEMENT', 'PPT/Workshop/Seminars etc', 'ITC LTD.', 'ITC LTD. is visiting the campus for their Leadership Talk with final year students who are passing out June, 2016.Date : 30th JULY, 2015  [ THURSDAY] Venue : KALIDAS AUDITORIUMTime: 6.45 p.m. Eligible', '90018', '29-07-2015 15:57', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(95, '48', 'INTERNSHIP', 'General', 'American Express', 'Job description of American Express Summer Interns is attached  for information all  concerned.Chairman, CDC', '90033', '29-07-2015 12:01', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/48.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(96, '47', 'INTERNSHIP', 'Urgent', 'HINDUSTAN UNILEVER LTD.', 'Dear student ,PFa the list of student who have completed the application for HINDUSTAN UNILEVER LTD.Those students who have submitted their CV and not filled the HINDUSTAN UNILEVER LTD. form as per th', '11009', '29-07-2015 11:37', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/47.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(97, '46', 'INTERNSHIP', 'CV Submission', 'American Express', '', '90033', '29-07-2015 10:05', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/46.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(98, '45', 'PLACEMENT', 'Urgent', 'HackerRank', 'We''re pleased to share notification on CodeNation''s CodeAgon. The 4 hour long coding challenge starts on 15th August, 8 pm IST. Here is a glimpse of the great rewards up for grabs: - Cash prizes worth', '90018', '29-07-2015 09:40', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(99, '44', 'PLACEMENT', 'PPO', 'PROBE EQUITY RESEARCH', 'PROBE EQUITY RESEARCH have extended 01 (ONE)   Pre-placement Offer (PPO) to the following student:ABHISHEK GAUTAM11MA20002CTC Details :Rs.62,500/- pm (Rs.7.5 LPA) The above student  is required to sub', '90018', '28-07-2015 16:33', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(100, '43', 'INTERNSHIP', 'Schedule', 'Texas Instruments', 'Texas Instruments  will conduct online test as per schedule given below in connection with Summer Internship- 2016 selection.Date: 29.07.2015 - 6.00 p.m.  sharpVenue: PC labs of Takshila ComplexAll  t', '90033', '28-07-2015 15:54', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/43.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(101, '42', 'PLACEMENT', 'PPO', 'Futures First Info Services Pvt. Ltd.', 'FUTURE FIRST have extended 01 (ONE)   Pre-placement Offer (PPO) to the following student:12IM10019PATEL SHUGUN VINITCTC Details :Rs.60,000/- pmOne time confirmation bonus : Rs.1,00,000The above studen', '90018', '28-07-2015 15:45', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(102, '41', 'INTERNSHIP', 'Urgent', 'Nomura', 'Students from the below mentioned departments who applied for both the profiles (ABS Research &amp; FI Quant) of Nomura are requested to fill in their preferences in the following link latest by 7.00 ', '90033', '28-07-2015 15:24', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(103, '40', 'PLACEMENT', 'PPO', 'INTUIT', 'INTUIT have extended 01 (ONE) more Pre-placement Offer (PPO) to the following student:11MA20005AGGIDI VINEEL RAJACTC details are as follows:  Base  1,200,000/-  IPI  120,000/-  RSUs  750,000/-  Sign-O', '90018', '27-07-2015 17:18', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(104, '39', 'PLACEMENT', 'PPO', 'EZDI', 'EZDI have extended 04 (FOUR) Pre-placement Offer (PPO) to the following students:1DEVASHISH12CS100172KUMAR ABHISHEK12CS100283SAI SANDEEP RANGISETTI12CS100434AYUSH SHUKLA11MA20014CTC DETAILS :Fixed Sal', '90018', '27-07-2015 16:35', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(105, '38', 'INTERNSHIP', 'Urgent', 'HINDUSTAN UNILEVER LTD.', 'The  Deadline  for  applying  for the  online portal of  Hindustan Unilever has been  extended  up to 8.00 p.m. today (27.07.2015). The defaulters should apply to the online portal immediately   faili', '90033', '27-07-2015 16:18', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/38.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(106, '37', 'INTERNSHIP', 'Urgent', 'Nomura', '', '90033', '27-07-2015 15:37', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(107, '36', 'PLACEMENT', 'PPO', 'QUANTIPHI ANALYTICS SOLUTIONS', 'QUANTIPHI ANALYTICS SOLUTIONS have extended 01 (ONE) Pre-placement Offer (PPO) to the following student:112IE10013KARANAM SAI RAVI TEJAAnnual Remuneration :Fixed CTC : 5,00,000Performance linked incen', '90018', '27-07-2015 15:36', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(108, '35', 'PLACEMENT', 'Date extension', 'Registration for Final Placement', 'The deadline for Registration of Final Placement 2015-16 has been extended till midnight of 2nd August, 2015.Chairman, CDC', '90018', '27-07-2015 13:00', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(109, '34', 'PLACEMENT', 'PPO', 'HINDUSTAN UNILEVER LTD', 'HINDUSTAN UNILEVER LTD have extended 01 (ONE) Pre-placement Offer (PPO) to the following students:1.11CH30004ANUSHKA GUPTAThe above students  are required to submit their written acceptance/rejection ', '90018', '27-07-2015 12:52', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(110, '33', 'INTERNSHIP', 'Date extension', 'Goldman Sach.', 'The deadline for CV submission in connection with summer internship selection of Goldman Sachs ( Stg.) has been extended till 10.00 A.M. on 28.07.2015.All  the  concerned should note.Chairman, CDC', '90033', '27-07-2015 12:41', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(111, '32', 'INTERNSHIP', 'Date extension', 'Microsoft IDC', 'The deadline for CV submission in connection with summer internship selection of Microsoft IDC has been extended till 5 P.M. on 27.07.2015. Also the online test as per schedule given below in connecti', '11009', '27-07-2015 12:16', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(112, '30', 'PLACEMENT', 'PPO', 'INTUIT', 'INTUIT have extended 04 (FOUR) Pre-placement Offer (PPO) to the following students:112CS10009Avantsa Naga Rajitha 211MA20007Aman Aniket 311MA20028Maneesh Bhunwal 411MA20017Bihani Pradeep Gaurishankar ', '90018', '27-07-2015 10:56', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(113, '29', 'INTERNSHIP', 'Additional requirement', 'ITC Limited', 'ITC  Limited  has agreed to consider B. Tech/ Dual Degree  Industrial and System Engineering .Hence, Interested and eligible students as per internship notification form (INF) available in their ERP a', '90033', '24-07-2015 19:13', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(114, '28', 'INTERNSHIP', 'Schedule', 'Microsoft', 'Microsoft will conduct online test as per schedule given below in connection with Summer Internship- 2016 selection.Date: 27.07.2015 -  5.30 p.m.Venue: PC labs of Takshila ComplexAll the applicants mu', '90033', '24-07-2015 17:36', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(115, '27', 'INTERNSHIP', 'Schedule', 'Face Book', 'Face book will conduct online test as per schedule given below in connection with Summer Internship- 2016 selection.Date: 26.07.2015 - Sharp 9.00 A.M.Venue: PC labs of Takshila ComplexAll the applican', '90033', '24-07-2015 17:22', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(116, '25', 'INTERNSHIP', 'CV Submission', 'As mentioned', 'The  deadline for CV submission  in connection with  summer  internship  selection of  following  companies  has  been  extended till 09 A.M. on 24.07.2015. 1.Deutsche CIB Centre2.Face Book3.Goldman S', '90033', '23-07-2015 17:51', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(117, '24', 'INTERNSHIP', 'General', 'FEEDBACK FORMS', 'All  the  students  who have  completed  summer  internship (compulsory)   during  May-July 2015 are   required to upload  their feedback form/certificates  in their  ERP Account after proper  verific', '90033', '23-07-2015 15:32', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(118, '23', 'INTERNSHIP', 'CV Submission', 'ITC Limited', 'ITC Limited   invites application for summer internship selection (May-July, 2016)  Interested and eligible students as per internship notification form (INF) available in their ERP account are requir', '90033', '23-07-2015 12:25', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(119, '22', 'INTERNSHIP', 'CV Submission', 'Nomura', '', '90033', '22-07-2015 16:46', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/22.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(120, '21', 'INTERNSHIP', 'CV Submission', 'Nomura -Profile-2', '', '90033', '22-07-2015 16:44', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/21.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(121, '20', 'INTERNSHIP', 'CV Submission', 'HINDUSTAN UNILEVER LTD.', 'Chemical engineering students  applying  for Hindustan Unilever should note  the following.They  have to apply only one profile i.e  either R&amp;D  or  Supply Chain. If  any student applied  both the', '90033', '21-07-2015 17:33', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(122, '19', 'INTERNSHIP', 'CV Submission', 'HINDUSTAN UNILEVER LTD.', 'Hindustan Unilever has  agreed to consider Electrical Engineering ( both  B.Tech. and  Dual degree)nterested and eligible students as per internship notification form (INF) available in their ERP acco', '90033', '21-07-2015 17:27', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(123, '18', 'PLACEMENT', 'PPO', 'MICROSOFT', 'Microsoft have extended 10 (TEN) Pre-placement Offer (PPO) to the following students:112CS10062Agnivo Saha212CS10004Akshay Gupta312CS10056Bhargavi Paranjape412CS10061Megha Jhunjhunwala512CS10037Prudhv', '90018', '21-07-2015 12:40', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(124, '17', 'INTERNSHIP', 'General', 'TATA STEEL', 'The  following  students are advised  to collect their certificates and Cheques  in connection with  their internship at Tata Steel from  CDC office on or  before 24th July, 2015 positively.1. Boddu L', '90033', '21-07-2015 12:24', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate');
INSERT INTO `erp` (`id`, `cell1`, `type`, `cell3`, `company`, `description`, `cell6`, `date`, `link`, `cell9`, `cell10`) VALUES
(125, '16', 'INTERNSHIP', 'CV Submission', 'Nomura -Profile-2', 'Nomura invites application for summer internship selection (May-July, 2016) ( profile-2( Global Markets  ABS  Research)Interested and eligible students as per internship notification form (INF) availa', '90033', '21-07-2015 12:07', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(126, '15', 'PLACEMENT', 'Schedule', '1st Pre-Assessment Test for students who have registered for placement 2016', 'The 1st employ ability test for students appearing for placement 2016 has been scheduled on 5th &amp; 6th of September 2015. All students enrolling for Placement must take the Pre-Assessment test as t', '90018', '20-07-2015 17:41', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(127, '14', 'INTERNSHIP', 'CV Submission', 'Face Book', 'Face Book invites application for summer internship selection (May-July, 2016)Interested and eligible students as per internship notification form (INF) available in their ERP account are required to ', '90033', '20-07-2015 16:58', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(128, '13', 'INTERNSHIP', 'Additional requirement', 'Nomura', 'Nomura has agreed to consider the following additional courses ( 4th yr. integrated M.sc.) for summer internship selection (May-July, 2016)1 Chemistry2.Applied Geology3.Exploration Geophysics4.Physics', '90033', '20-07-2015 12:15', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(129, '11', 'INTERNSHIP', 'CV Submission', '1st  Day (1st Aug.)  Companies', 'The  following companies invites application for summer internship selection (May-July, 2016)1. RB2. Hindustan Uniliver3. Nomura4. Texas  InstrumentsInterested and eligible students as per internship ', '90033', '20-07-2015 09:26', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(130, '10', 'PLACEMENT', 'Urgent', 'Registration for Final Placement', 'The details registration procedure for final placement 2015-16 is in the attachment.The last date for registration (for all students) on or before 26th July, 2015 (midnight).Chairman, CDC', '90018', '17-07-2015 10:11', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/10.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(131, '9', 'INTERNSHIP', 'CV Submission', 'DB  Centre', 'DB Centre invites application for summer internship selection (May-July, 2016)Interested and eligible students as per internship notification form (INF) available in their ERP account are required to ', '90033', '13-07-2015 17:35', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(132, '8', 'PLACEMENT', 'Urgent', 'Systems Development  Lab', 'The Advt for Software Engineer - Bigdata/Analytics profile is in the attachment.', '90018', '13-07-2015 17:14', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/8.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(133, '7', 'PLACEMENT', 'Urgent', 'Systems Development  Lab', 'Advt for UI Developer - Bigdata/Analytics profile is in the attachment.', '90018', '13-07-2015 17:12', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/7.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(134, '6', 'PLACEMENT', 'Urgent', 'Facebook', 'Facebook is looking for talented and experienced development lead to join GSS Insights team in Hyderabad, India. Our team provides scaled insights for facebook advertisers globally, and partners with ', '90018', '13-07-2015 17:10', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(135, '5', 'PLACEMENT', 'Urgent', 'NATIONAL COUNCIL FOR CEMENT AND BUILDING MATERIALS', 'Notice is in the attachment.', '90018', '13-07-2015 17:06', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/5.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate'),
(136, '4', 'PLACEMENT', 'Result', 'Vedanta', 'The following student have been selected by Vedanta Limited - Iron Ore, Goa for final placement. 1.       Srinivas Rohit2.       Rajeev Ranjan3.       Sunil GudiseThe above student is advised to give ', '11009', '06-07-2015 16:08', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(137, '3', 'PLACEMENT', 'Urgent', 'SANTENT', '', '90018', '09-06-2015 16:53', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(138, '2', 'PLACEMENT', 'Urgent', 'EATON', '', '90018', '09-06-2015 16:52', '&lt;a title='''' href=''javascript:void(0);'' onclick=''TPNotice(&quot;&quot;);''--&gt;', 'Upload', 'Deactivate'),
(139, '1', 'PLACEMENT', 'Urgent', 'Smartican', '', '90018', '09-06-2015 16:51', '&lt;a title=''Download'' href=''javascript:void(0);'' onclick=''TPNotice(&quot;/DATA/ARCHIVE/TRAINGANDPLACEMNT/2015-2016/NOTICE/1.pdf&quot;);''--&gt;Download', 'Upload', 'Deactivate');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
